/*drop table if exists "Films" cascade;
drop table if exists "Users" cascade;
drop table if exists "Genres" cascade;
drop table if exists "Genres_to_Films" cascade;
drop table if exists "Mpa" cascade;
drop table if exists "Friends" cascade;
drop table if exists "Film_Likes" cascade;*/

CREATE TABLE if not exists "Films"
(
    "Film_ID"      int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name"         varchar                              NOT NULL,
    "Description"  varchar                              NOT NULL,
    "Rating_ID"    int                                  NOT NULL,
    "Release_Date" timestamp                            NOT NULL,
    "Duration"     int                                  NOT NULL,
    CONSTRAINT "PK_Films" PRIMARY KEY ("Film_ID")
);

CREATE TABLE if not exists "Genres"
(
    "Genre_ID" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name"     varchar                              NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Genre_ID")
);

CREATE TABLE if not exists "Genres_to_Films"
(
    "Film_ID"  int NOT NULL,
    "Genre_ID" int NOT NULL,
    CONSTRAINT "PK_Genres_to_Films" PRIMARY KEY ("Genre_ID", "Film_ID")
);

CREATE TABLE if not exists "Mpa"
(
    "Rating_ID" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name"      varchar                              NOT NULL,
    CONSTRAINT "PK_Ratings" PRIMARY KEY ("Rating_ID")
);

CREATE TABLE if not exists "Users"
(
    "User_ID"  int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email"    varchar                              NOT NULL,
    "Login"    varchar                              NOT NULL,
    "Name"     varchar                              NOT NULL,
    "Birthday" TimeStamp                            NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("User_ID")
);

CREATE TABLE if not exists "Friends"
(
    "User_A" int NOT NULL,
    "User_B" int NOT NULL,
    CONSTRAINT "PK_Friends" PRIMARY KEY ("User_A", "User_B")
);

CREATE TABLE if not exists "Film_Likes"
(
    "User_ID" int NOT NULL,
    "Film_ID" int NOT NULL,
    CONSTRAINT "PK_Film_Likes" PRIMARY KEY ("User_ID", "Film_ID")
);
ALTER TABLE "Genres_to_Films"
    ADD CONSTRAINT if not exists "fk_Genres_to_Films_Film_ID" FOREIGN KEY ("Film_ID")
        REFERENCES "Films" ("Film_ID");

ALTER TABLE "Genres_to_Films"
    ADD CONSTRAINT if not exists "fk_Genres_to_Films_Genre_ID" FOREIGN KEY ("Genre_ID")
        REFERENCES "Genres" ("Genre_ID");

ALTER TABLE "Films"
    ADD CONSTRAINT if not exists "fk_Films_Rating_ID" FOREIGN KEY ("Rating_ID")
        REFERENCES "Mpa" ("Rating_ID");

ALTER TABLE "Friends"
    ADD CONSTRAINT if not exists "fk_Friends_User_A" FOREIGN KEY ("User_A")
        REFERENCES "Users" ("User_ID");

ALTER TABLE "Friends"
    ADD CONSTRAINT if not exists "fk_Friends_User_B" FOREIGN KEY ("User_B")
        REFERENCES "Users" ("User_ID");

ALTER TABLE "Film_Likes"
    ADD CONSTRAINT if not exists "fk_Film_Likes_User_ID" FOREIGN KEY ("User_ID")
        REFERENCES "Users" ("User_ID");

ALTER TABLE "Film_Likes"
    ADD CONSTRAINT if not exists "fk_Film_Likes_Film_ID" FOREIGN KEY ("Film_ID")
        REFERENCES "Films" ("Film_ID");